Twitter/Twitter.App/Controllers/NotificationsController.cs
using System.Linq;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Twitter.App.Models.ViewModels;
using Twitter.Data.UnitOfWork;

namespace Twitter.App.Controllers
{
    public class NotificationsController : BaseController
    {
        public NotificationsController(ITwitterData data) : base(data)
        {
        }

        public ActionResult MarkAsRead(int notificationId)
        {
            var notification = this.Data.Notifications.Find(notificationId);

            notification.Seen = true;
            this.Data.SaveChanges();

            return RedirectToAction("AllNotifications");
        }

        public ActionResult GetUnread()
        {
            var loggedUserId = this.User.Identity.GetUserId();

            var count = this.Data.Notifications.All()
                .Count(n => n.ReceiverId == loggedUserId &&
                            !n.Seen && (n.SenderId != loggedUserId));

            return PartialView(count);
        }

        [Authorize]
        public ActionResult GetLastNotification()
        {
            var loggedUserId = this.User.Identity.GetUserId();
            var user = this.Data.Users.Find(loggedUserId);

            var notification = user
                .ReceivedNotifications
                .OrderByDescending(n => n.CreatedAt)
                .Take(1)
                .AsQueryable()
                .Select(NotificationViewModel.Create);

            return View(notification);
        }

        [Authorize]
        public ActionResult AllNotifications()
        {
            var loggedUserId = this.User.Identity.GetUserId();
            var user = this.Data.Users.Find(loggedUserId);

            var notifications = user
                .ReceivedNotifications
                .OrderByDescending(n => n.CreatedAt)
                .AsQueryable()
                .Select(NotificationViewModel.Create);

            return View(notifications);
        }
    }
}

Twitter/Twitter.App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Profile", "ShowProfile", "Users")</li>
                        <li><a href="@Url.Action("GetLastNotification", "Notifications")">Notifications @{Html.RenderAction("GetUnread", "Notifications");}</a></li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/unobtrusiveJquery")
    @Scripts.Render("~/bundles/signalR")
    @RenderSection("scripts", required: false)
</body>
</html>

Twitter/Twitter.App/Views/Shared/_UserProfilePartial.cshtml
@using Microsoft.AspNet.Identity
@if (Request.IsAuthenticated)
{
    
}